from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import numpy as np
import sys
import os

class Ui_Form(object):
    def setupUi(self, Form, size=(256, 256)):
        Form.setObjectName("Form")
        self.buttion_W, self.buttion_H = 107, 37
        self.pushButton = QPushButton(Form)
        self.pushButton.setFixedSize(self.buttion_W, self.buttion_H)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QPushButton(Form)
        self.pushButton_2.setFixedSize(self.buttion_W, self.buttion_H)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QPushButton(Form)
        self.pushButton_3.setFixedSize(self.buttion_W, self.buttion_H)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QPushButton(Form)
        self.pushButton_4.setFixedSize(self.buttion_W, self.buttion_H)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QPushButton(Form)
        self.pushButton_5.setFixedSize(self.buttion_W, self.buttion_H)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QPushButton(Form)
        self.pushButton_6.setFixedSize(self.buttion_W, self.buttion_H)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QPushButton(Form)
        self.pushButton_7.setFixedSize(self.buttion_W, self.buttion_H)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QPushButton(Form)
        self.pushButton_8.setFixedSize(self.buttion_W, self.buttion_H)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QPushButton(Form)
        self.pushButton_9.setFixedSize(self.buttion_W, self.buttion_H)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QPushButton(Form)
        self.pushButton_10.setFixedSize(self.buttion_W, self.buttion_H)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QPushButton(Form)
        self.pushButton_11.setFixedSize(self.buttion_W, self.buttion_H)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QPushButton(Form)
        self.pushButton_12.setFixedSize(self.buttion_W, self.buttion_H)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QPushButton(Form)
        self.pushButton_13.setFixedSize(self.buttion_W, self.buttion_H)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_26 = QPushButton(Form)
        self.pushButton_26.setFixedSize(self.buttion_W, self.buttion_H)
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QPushButton(Form)
        self.pushButton_27.setFixedSize(self.buttion_W, self.buttion_H)
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QPushButton(Form)
        self.pushButton_28.setFixedSize(self.buttion_W, self.buttion_H)
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QPushButton(Form)
        self.pushButton_29.setFixedSize(self.buttion_W, self.buttion_H)
        self.pushButton_29.setObjectName("pushButton_29")
        # self.pushButton_29 = QPushButton(Form)
        # self.pushButton_29.setFixedSize(self.buttion_W, self.buttion_H)
        # self.pushButton_29.setObjectName("pushButton_29")
        # self.pushButton_30 = QPushButton(Form)
        # self.pushButton_30.setFixedSize(self.buttion_W, self.buttion_H)
        # self.pushButton_30.setObjectName("pushButton_30")     

        self.graphicsView = QGraphicsView(Form)
        self.graphicsView.setFixedSize(size[0], size[1])
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QGraphicsView(Form)
        self.graphicsView_2.setFixedSize(size[0], size[1])
        self.graphicsView_2.setObjectName("graphicsView_2") 
        self.graphicsView_3 = QGraphicsView(Form)
        self.graphicsView_3.setFixedSize(size[0]//2, size[1]//2)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.graphicsView_4 = QGraphicsView(Form)
        self.graphicsView_4.setFixedSize(size[0], size[1])
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.graphicsView_5 = QGraphicsView(Form)
        self.graphicsView_5.setFixedSize(size[0]//2, size[1]//2)
        self.graphicsView_5.setObjectName("graphicsView_5")

        self.clickButtion1 = QRadioButton(Form)
        self.clickButtion1.setText('Fix Sample')
        self.clickButtion1.setChecked(True)
        self.clickButtion2 = QRadioButton(Form)
        self.clickButtion2.setText('Random Sample')
        self.clickButtion3 = QRadioButton(Form)
        self.clickButtion3.setText('Random Instance')
        self.clickButtion4 = QRadioButton(Form)
        self.clickButtion4.setText('Ref Instance')

        self.label1 = QLabel(Form)
        self.label1.setText('Ref Instance Id: -1')
        self.label0 = QLabel(Form)
        self.label0.setText('Tag Instance Id: -1')

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.edit)
        self.pushButton_2.clicked.connect(Form.open)
        self.pushButton_3.clicked.connect(Form.open_mask)
        self.pushButton_29.clicked.connect(Form.open_ref)
        self.pushButton_4.clicked.connect(Form.clear)
        self.pushButton_5.clicked.connect(Form.undo)
        self.pushButton_6.clicked.connect(Form.save_img)
        self.pushButton_7.clicked.connect(Form.bg_mode)
        self.pushButton_8.clicked.connect(Form.hair_mode)
        self.pushButton_9.clicked.connect(Form.face_mode)
        self.pushButton_10.clicked.connect(Form.clothes_mode)
        self.pushButton_11.clicked.connect(Form.pants_mode)
        self.pushButton_12.clicked.connect(Form.body_mode)
        self.pushButton_13.clicked.connect(Form.shoes_mode)
        self.pushButton_26.clicked.connect(Form.increase)
        self.pushButton_27.clicked.connect(Form.decrease)
        self.pushButton_28.clicked.connect(Form.sketch_mode)

        self.grid0 = QGridLayout()
        self.grid0.addWidget(self.pushButton_2, 0,0,1,1)
        self.grid0.addWidget(self.pushButton_3, 1,0,1,1)
        self.grid0.addWidget(self.pushButton_29, 2,0,1,1)
        self.grid0.addWidget(self.pushButton_4, 0,1,1,1)
        self.grid0.addWidget(self.pushButton_5, 1,1,1,1)
        self.grid0.addWidget(self.pushButton_6, 2,1,1,1)
        self.grid0.addWidget(self.pushButton, 0,2,1,1)
        self.grid0.addWidget(self.pushButton_26, 1,2,1,1)
        self.grid0.addWidget(self.pushButton_27, 2,2,1,1)

        self.grid00 = QGridLayout()
        self.grid00.addWidget(self.clickButtion1, 0,0,1,1)
        self.grid00.addWidget(self.clickButtion2, 1,0,1,1)
        self.grid00.addWidget(self.clickButtion3, 2,0,1,1)
        self.grid00.addWidget(self.clickButtion4, 3,0,1,1)
        self.grid00.addWidget(self.label1, 4,0,1,1)
        self.grid00.addWidget(self.label0, 5,0,1,1)

        self.grid1 = QGridLayout()
        self.grid1.addWidget(self.pushButton_7, 0,0,1,1)
        self.grid1.addWidget(self.pushButton_8, 0,1,1,1)
        self.grid1.addWidget(self.pushButton_9, 0,2,1,1)
        self.grid1.addWidget(self.pushButton_10, 0,3,1,1)
        self.grid1.addWidget(self.pushButton_11, 0,4,1,1)
        self.grid1.addWidget(self.pushButton_12, 0,5,1,1)
        self.grid1.addWidget(self.pushButton_13, 0,6,1,1)
        self.grid1.addWidget(self.pushButton_28, 0,7,1,1)

        # self.grid3 = QGridLayout()
        # self.grid3.addLayout(self.AddWidgt(self.graphicsView_3, "Original Image"), 0,0,1,1)
        # self.grid3.addLayout(self.AddWidgt(self.graphicsView_5, "Reference Image"),1,0,1,1)

        self.grid2 = QHBoxLayout()
        self.grid2.addLayout(self.AddWidgt(self.graphicsView, "Mask"))
        self.grid2.addLayout(self.AddWidgt(self.graphicsView_2, "Sketch"))
        self.grid2.addLayout(self.AddWidgt(self.graphicsView_4, "Result"))

        self.grid3 = QHBoxLayout()
        self.grid3.addLayout(self.AddWidgt(self.graphicsView_3, "Original Image"))
        self.grid3.addLayout(self.AddWidgt(self.graphicsView_5, "Reference Image"))

        self.grid4 = QHBoxLayout()
        self.grid4.addLayout(self.AddLayout(self.grid3, ""))
        self.grid4.addLayout(self.AddLayout(self.grid0, "Main Buttons"))
        self.grid4.addLayout(self.AddLayout(self.grid00, "Random Model"))

        # self.grid5 = QGridLayout()
        # self.grid5.addLayout(self.AddWidgt(self.graphicsView_3, "Original Image"), 0,0,1,1)
        # self.grid5.addLayout(self.AddWidgt(self.graphicsView_5, "Reference Image"), 1,0,1,1)
        # self.grid5.addLayout(self.AddWidgt(self.graphicsView, "Mask"), 0,1,2,2)
        # self.grid5.addLayout(self.AddWidgt(self.graphicsView_2, "Sketch"), 0,3,2,2)
        # self.grid5.addLayout(self.AddWidgt(self.graphicsView_4, "Result"), 0,5,2,2)

        mainLayout = QVBoxLayout()
        Form.setLayout(mainLayout)
        Form.resize(500, 500)
        mainLayout.addLayout(self.AddLayout(self.grid1, "Attributes"))
        mainLayout.addLayout(self.AddLayout(self.grid2, ""))
        mainLayout.addLayout(self.AddLayout(self.grid4, ""))
        
        # connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "INADES"))
        self.pushButton.setText(_translate("Form", "Edit"))
        self.pushButton_2.setText(_translate("Form", "Open Image"))
        self.pushButton_3.setText(_translate("Form", "Open Mask"))
        self.pushButton_29.setText(_translate("Form", "Open Reference"))
        self.pushButton_4.setText(_translate("Form", "Clear"))
        self.pushButton_5.setText(_translate("Form", "Undo"))
        self.pushButton_6.setText(_translate("Form", "Save Image"))
        self.pushButton_7.setText(_translate("Form", "BackGround"))
        self.pushButton_8.setText(_translate("Form", "Hair"))
        self.pushButton_9.setText(_translate("Form", "Face"))
        self.pushButton_10.setText(_translate("Form", "Clothes"))
        self.pushButton_11.setText(_translate("Form", "Pants"))
        self.pushButton_12.setText(_translate("Form", "Body"))
        self.pushButton_13.setText(_translate("Form", "Shoes"))
        self.pushButton_26.setText(_translate("Form", "+"))
        self.pushButton_27.setText(_translate("Form", "-"))
        self.pushButton_28.setText(_translate("Form", "sketch"))

    def AddLayout(self, widget, title=''):
        widgetLayout = QVBoxLayout()
        widgetBox = QGroupBox()
        if title != '':
            widgetBox.setTitle(title)
        widgetBox.setAlignment(Qt.AlignCenter)
        widgetBox.setLayout(widget)
        widgetLayout.addWidget(widgetBox)

        return widgetLayout


    def AddWidgt(self, widget, title):
        widgetLayout = QVBoxLayout()
        widgetBox = QGroupBox()
        widgetBox.setTitle(title)
        widgetBox.setAlignment(Qt.AlignCenter)
        vbox_t = QGridLayout()
        vbox_t.addWidget(widget,0,0,1,1)
        widgetBox.setLayout(vbox_t)
        widgetLayout.addWidget(widgetBox)

        return widgetLayout

if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    Form = QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

